### ISSUE TITLE
RN 0.18 extends ReactActivity

### ISSUE THREAD

**Issue by alvinwoon** [aakashns/react-native-dialogs#10]
Since we can't extend 2 activities in java, is there anyway to keep using this library post-0.18?

**Comment by ncnlinh** [comment]
:+1: same issue

**Comment by janicduplessis** [comment]
What I did as a workaround is copy https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java in my project and make it extend `FragmentActivity` instead of `Activity` and then use that as your base activity instead of `ReactActivity`.

**Comment by rpopovici** [comment]
you can take a look at https://github.com/nucleartux/react-native-date they fixed the problem here https://github.com/nucleartux/react-native-date/commit/1d11fa6d85c7f6165128beaa53623ec61980cd2b

**Comment by aakashns** [comment]
Hey guys, thanks for bringing up the issue. Really sorry I haven't been able to get to the fix. I'm a little occupied at the moment. Would you consider adding a pull request?

**Comment by janicduplessis** [comment]
@rpopovici Thanks for pointing that out, I submitted a PR to do a similar change.

**Comment by sdg9** [comment]
Any chance you can publish this to npm? Latest version doesn't include this change.
