### ISSUE TITLE
DialogAndroid.prompt set OptionsCommon' content not working on Android

### ISSUE THREAD

**Issue by ssshen** [aakashns/react-native-dialogs#103]
RN version 0.56.0
react-native-dialogs version: 1.0.2

```
let { action, text } = await DialogAndroid.prompt("title", "tips", {
                positiveText: "confirm",
                negativeText: "cancel",
                content: "notes"
});
```
the content doesn't show when push dialog

how to show dialog with content?

**Comment by Noitidart** [comment]
Content options does nothing. Content option is now the 2nd argument of `prompt`.

**Comment by Noitidart** [comment]
Closing as this is a question resolved by documentation. If you have more questions, definitely ask away.
