### ISSUE TITLE
1.0.3

### ISSUE THREAD

**Issue by Noitidart** [aakashns/react-native-dialogs#105]
I'm getting ready for a 1.0.3 release. Anything anyone wants to see in 1.0.3? This realease is mainly for new features of #104 and #102.

**Comment by Phecda** [comment]
I noticed that a commit not is merged , please wait for a second

**Comment by Noitidart** [comment]
Published - https://github.com/aakashns/react-native-dialogs/commit/72080ce7196d63a60022e0596d7c57e528b11702
