### ISSUE TITLE
Duplicate type OptionsCheckbox

### ISSUE THREAD

**Issue by ratson** [aakashns/react-native-dialogs#111]
https://github.com/aakashns/react-native-dialogs/blob/master/DialogAndroid.js#L16 and https://github.com/aakashns/react-native-dialogs/blob/master/DialogAndroid.js#L49 is duplicated.

@aakashns @Noitidart Should they be different?

**Comment by Noitidart** [comment]
Thank you for catching and pointing this out. These should definitely be different. The first "OptionsCheckbox" is to add a single checkbox as seen in screenshots here - https://github.com/aakashns/react-native-dialogs/pull/86#issuecomment-393408317

The second "OptionsCheckbox" is key/value pairs accepted if the `listType` is set to `DialogAndroid.listCheckbox`.

I think I'll rename the second one to `OptionsCheckboxList`. I will also rename `OptionsRadio` to `OptionsRadioList`. What do you think?

**Comment by ratson** [comment]
Perfect!
