### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNative.NativeModules.DialogAndroid.show'

### ISSUE THREAD

**Issue by maelfosso** [aakashns/react-native-dialogs#114]
Hello 
I'm getting that error and I don't understand why ?

Here is my code 
```
_selectForm = async () => {
    try {
      const { selectedItem } = await DialogAndroid.showPicker('Pick a form', null, {
        items: [
          { label:'12 Months', id:'12-months' },
          { label:'16 Months', id:'16-months' },
          { label:'20 Months', id:'20-months' }
        ]
      });
      if (selectedItem) {
        // when negative button is clicked, selectedItem is not present, so it doesn't get here
        console.log('You selected item:', selectedItem);
        this.props.navigation.navigate("CollectingDataScreen", {
          form: selectedItem
        });
      }
    } catch(e) {
      console.log("DIALOG ANDROID EROOR ... ", e);
    }
  }
```

And after installing, the version from `package.json` is `"react-native-dialogs": "^1.0.4"`

**Comment by TxusBlack** [comment]
I have the same error 😞

**Comment by Noitidart** [comment]
Excuse me missing this issue, thanks @TxusBlack for the bump. I'll take a look today.

**Comment by Noitidart** [comment]
I just tried this, it didn't give me an error on 1.0.5:

```
        const options: { label:string, value:string }[] = [
            { label: 'Most Votes (Likes + Dislikes)', value: 'thumbs'           },
            { label: 'Most Likes'                   , value: 'thumbs-up'        },
            { label: 'Most Dislikes'                , value: 'thumbs-down'      },
            { label: 'Recent Activity'              , value: 'recent'           },
            { label: 'Most Comments'                , value: 'comments'         },
            { label: 'Most Helpful Comments'        , value: 'helpful-comments' },
            { label: 'Cancel'                       , value: 'cancel'           }
        ];

            const { selectedItem } = await DialogAndroid.showPicker(PROMPT_TITLE, null, {
                items: options.slice(0, options.length-1), // no cancel button
                idKey: 'value',
                positiveText: null,
                negativeText: 'Cancel'
            });
```

Will try again to reproduce your error soon (tomorrow'ish hopefully).

**Comment by TxusBlack** [comment]
Look, I'm having this error:

![59443153_2066218993678616_583027078694174720_n](https://user-images.githubusercontent.com/13071556/57203669-a74acf80-6f77-11e9-85f9-1a9ed1a7633f.png)

And in this case, my code is:

`
dialog = () => {
    const options = [
        { label: 'Most Votes (Likes + Dislikes)', value: 'thumbs' },
        { label: 'Most Likes', value: 'thumbs-up' },
        { label: 'Most Dislikes', value: 'thumbs-down' },
        { label: 'Recent Activity', value: 'recent' },
        { label: 'Most Comments', value: 'comments' },
        { label: 'Most Helpful Comments', value: 'helpful-comments' },
        { label: 'Cancel', value: 'cancel' }
      ];

      const { selectedItem } = await DialogAndroid.showPicker('im a title', null, {
        items: options.slice(0, options.length - 1), // no cancel button
        idKey: 'value',
        positiveText: null,
        negativeText: 'Cancel'
      });

      if (selectedItem) {
        // when negative button is clicked, selectedItem is not present, so it doesn't get here
        console.log('You picked:', selectedItem);
      }
}
`

`
<TouchableOpacity style={styles.lastItem} onPress={this.dialog}>
    <Text style={styles.name}>{this.state.notificationSelected}</Text>
</TouchableOpacity>
`

**Comment by Noitidart** [comment]
This is way weird. Are you using latest react-native version?

**Comment by TxusBlack** [comment]
I'm using this:

```
react-native-cli: 2.0.1
react-native: 0.59.4
```

**Comment by Noitidart** [comment]
That's real odd. Do you think maybe react-native-cli has something to do with it? I dont use that.

**Comment by TxusBlack** [comment]
I do not think so. Anyway, here's also my node, yarn and npm version.

```
Node: v8.15.0
npm: 6.4.1
yarn: 1.13.0
```

**Comment by vonovak** [comment]
this error is caused by the fact that the native module is not correctly linked; follow https://github.com/aakashns/react-native-dialogs#manual-linking or if you're on RN0.60 or newer, compiling should just work because of autolinking
