### ISSUE TITLE
Examples are missing in branch "Master"

### ISSUE THREAD

**Issue by Beatsleigher** [aakashns/react-native-dialogs#14]
The examples are missing from the master branch.
Extremely frustrating, as all links (advanced example) point to a 404.

Please fix.

**Comment by Beatsleigher** [comment]
I'm sorry to say this, but if you do not even take care of your projects (open source projects, not to mention!), then it's no wonder that this won't take off properly...

**Comment by aakashns** [comment]
Hi @Beatsleigher, sorry for causing you frustration. I've updated the README to point to the right location.
