### ISSUE TITLE
Change color theme

### ISSUE THREAD

**Issue by VinceBT** [aakashns/react-native-dialogs#20]
Changing the color of buttons and input as following

``` jsx
var dialog = new DialogAndroid();
let options = {
  color: '#1E90FF',
  title: 'Title',
  input: {
    hint: 'Placeholder',
    prefill: 'Prefill',
    type: 1,
    callback: (value) => {
      console.log(value);
    }
  },
  positiveText: 'Update',
  negativeText: 'Cancel'
};
dialog.set(options);
dialog.show();
```

**Comment by ashleydw** [comment]
I would like to change the button colours too, but rather than as an option, they should use the global styles.xml, as "native" react-native Alert dialogs do

**Comment by iRoachie** [comment]
Doesn't work for me

**Comment by vonovak** [comment]
please see https://github.com/aakashns/react-native-dialogs/blob/2cd553fa65a643147ecbb325d574bcc6d9c946c5/android/src/main/java/com/aakashns/reactnativedialogs/modules/DialogAndroid.java#L54

You may also style this using the xml styling features of android, for example 

```
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
     
        <!-- color in dialogs, default color for spinners etc -->
        <item name="colorAccent">@color/azureTwo</item>

    </style>
```

**Comment by sam9010** [comment]
i want to bold text style in  positiveText
how?
