### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by linonetwo** [aakashns/react-native-dialogs#23]
By calling 
dialog.show({});

In DialogAndroid.js line 67
NativeModules.DialogAndroid.show(finalOptions, callbackFunc);

says undefined is not an object.

seems NativeModules.DialogAndroid is deprecated?

**Comment by saemie** [comment]
I'm having the same issue, did you find a solution?

**Comment by linonetwo** [comment]
@saemie No, I switch to react-native-model .....

**Comment by vonovak** [comment]
closing since there is very little information provided and the issue is old. feel free to reopen.
