### ISSUE TITLE
Can´t build my Android project

### ISSUE THREAD

**Issue by BigPun86** [aakashns/react-native-dialogs#24]
I receive following error output:

A problem occurred configuring project ':app'.

> Could not resolve all dependencies for configuration ':app:_debugCompile'.
> Could not find com.github.afollestad.material-dialogs:commons:8f8ab21.

**Comment by pengshaomin** [comment]
me to;

**Comment by BigPun86** [comment]
My fix was to put it in the top level build.gradle (rootproject/android/build.gradle)

`
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven { url "https://jitpack.io" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$projectDir/../../node_modules/react-native/android"
        }
    }
}

`

**Comment by duranmla** [comment]
@BigPun86 thanks for posting your solution, it works for me too. However, I think we can be agree into say that is the right way looking to this article: http://stackoverflow.com/questions/28295933/difference-between-build-gradleproject-and-build-gradlemodule 

@aakashns if you need any help with this project just let me know, I'm willing to help you.

**Comment by duranmla** [comment]
If we are agree into make the above update we can close this issue IMHO.

**Comment by duranmla** [comment]
Actually, if I place write:

```
repositories {
  maven { url 'https://jitpack.io' }
}
```

on the `android/app/gradle` but at the first level of the file I do not have the error. Despite of that I still getting a isue regarding the recyclerView after include this module into my project. 👎

**Comment by vonovak** [comment]
closing as outdated
