### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by 1ne8ight7even** [aakashns/react-native-dialogs#25]
I got the following error if i build my app:

`android/app/build/intermediates/exploded-aar/com.github.afollestad.material-dialogs/core/8f8ab21/res/values-v11/values-v11.xml:17:54-92 : No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').`

`:app:processDebugResources FAILED`

`FAILURE: Build failed with an exception.`

**Comment by 1ne8ight7even** [comment]
Solved here https://github.com/aakashns/react-native-dialogs/pull/26

**Comment by charliesbox** [comment]
having the same issue! please accept this PR

**Comment by aakashns** [comment]
Thanks @1ne8ight7even
