### ISSUE TITLE
prefill radio 

### ISSUE THREAD

**Issue by texas697** [aakashns/react-native-dialogs#31]
I am trying to set a default selection for a single choice list. I am trying this with no luck

```
  var options = {
            items: ['Data Entry', 'Notes', 'Take Picture'],
            positiveText: "Select",
            negativeText: "Cancel",
            title: this.state.selectedSubdivision.subdivisionName,
            input: { prefill: '0'},
            itemsCallbackSingleChoice: _menuSelect
        };
```

**Comment by charliesbox** [comment]
you need to add the `selectedIndex` property

`title: this.state.selectedSubdivision.subdivisionName,
 items: options,
 selectedIndex: 0,
 itemsCallbackSingleChoice: _menuSelect`

**Comment by vonovak** [comment]
the question is answered, this option is documented in readme.
