### ISSUE TITLE
'The callback show() exists in module DialogAndroid...'

### ISSUE THREAD

**Issue by QuantumKing** [aakashns/react-native-dialogs#44]
'...but only one callback may be registered to a function in a native module'

I keep getting this error. My configuration looks like this

``` js
const dialog = new DialogAndroid();
let newColumnName = this.state[columnName];
dialog.set({
  negativeText: 'Cancel',
  positiveText: 'Ok',
  onPositive: () => {
    if (this.state[columnName] !== newColumnName) {
      this.patchInvoice({ [columnName]: newColumnName });
    }
  },
  title,
  input: {
    prefill: newColumnName,
    allowEmptyInput: false,
    callback: (nextValue) => {
      newColumnName = nextValue;
    },
  },
  alwaysCallInputCallback: true,
});
dialog.show();
```

**Comment by QuantumKing** [comment]
Fixed it by putting the `onPositive` code inside the input `callback`. Issue arrises because the native module's `callback` is being invoked multiple times.

**Comment by pfeiffer** [comment]
I'm seeing this as well with:
```js
dialog.set({
  itemsCallback: () => { },
  dismissListener: () => {  },
});
```

**Comment by vunguyentuan** [comment]
I'm getting the same issue, any update on this?

**Comment by rodrigoxavier** [comment]
The @QuantumKing answer solve to me! Thank you.
My function is the following and it's working perfectly:

`var options = {
      title: I18n.t('observation').toUpperCase(),
      content: I18n.t('observation_desc'),
      positiveText: I18n.t('ok'),
      negativeText: I18n.t('cancel'),
      input: {
        allowEmptyInput: false,
        callback: (text) => {
          this.props.editContactObservation(text, contact, this.props.user.uid)
        },
      }
    };

      const dialog = new DialogAndroid();
      dialog.set(options);
      dialog.show();`

**Comment by aish1550** [comment]
Hi, Just seen this. I'm getting this too. Im not a JS wiz but using firebase, steup with npm firestack module and react native. Simply trying to get password reset working and for some reason getting the above error when they submit their email address. Anyone tell me what i'm doing wrong and how to fix this without speaking techie jargon?

**Comment by aish1550** [comment]
![image](https://cloud.githubusercontent.com/assets/8047739/26084200/5a2dfc68-39d2-11e7-96dc-46e6537a3eac.png)

**Comment by vonovak** [comment]
closed in favor of https://github.com/aakashns/react-native-dialogs/issues/57

my comment: yes, callback can only be invoked once. If you'd like to have your JS function to be called multiple times, we'd need to use events. This is currently not implemented but I'd merge a PR for this if anyone is interested.
