### ISSUE TITLE
IncompatibleClassChangeError during compilation after adding the package

### ISSUE THREAD

**Issue by varungupta85** [aakashns/react-native-dialogs#45]
I added this package to my app and when I run command `react-native run-android` to compile and run the app for `Android`, it ends with the below exception

```
java.lang.IncompatibleClassChangeError: The method 
     'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' 
     was expected to be of type virtual but instead was found to be of type direct 
```

This error is showing up for a different package `react-native-push-notification` but it is happening due to a mismatch between the `com.android.support` libraries. The default one included in `react-native` project is `v23.0.1` but the one included in the underlying [material-dialogs](https://github.com/afollestad/material-dialogs/blob/master/core/build.gradle) package is `v24.2.0`. This is causing the problem while compiling the app. There are multiple questions on [stackoverflow](http://stackoverflow.com/questions/37312340/incompatibleclasschangeerror-after-updating-to-android-build-tools-25-1-6-gcm) [regarding](http://stackoverflow.com/questions/37337393/android-google-cloud-messaging-gcm-token-generation-crash-after-firebase-relat) similar error which seem to suggest to downgrade the version to `v23` but I am not sure how to do it as the `material-dialogs` package is downloaded during build and is present in some gradle repository location.

Is it possible to downgrade the `com.android.support` used `material-dialogs` or if someone has come across this problem and were able to solve it, please share.

**Comment by ashleydw** [comment]
I also get this but using 0.0.15 version it works, this PR is the failing commit https://github.com/aakashns/react-native-dialogs/pull/33

**Comment by vonovak** [comment]
closing as it's super old
