### ISSUE TITLE
Build error on react-native 0.14.2

### ISSUE THREAD

**Issue by flyingmate** [aakashns/react-native-dialogs#5]
ReadableMapKeySeyIterator is changed to ReadableMapKeySetIterator on react-native 0.14.2
https://github.com/facebook/react-native/issues/3540

So I got this error below. 
After changed the class name on DialogAndroid.java file, it worked. 

/Users/james/Dropbox/Development/react/Builder/node_modules/react-native-dialogs/android/src/main/java/com/aakashns/reactnativedialogs/modules/DialogAndroid.java:15: error: cannot find symbol
import com.facebook.react.bridge.ReadableMapKeySeyIterator;
                                ^
  symbol:   class ReadableMapKeySeyIterator
  location: package com.facebook.react.bridge
/Users/james/Dropbox/Development/react/Builder/node_modules/react-native-dialogs/android/src/main/java/com/aakashns/reactnativedialogs/modules/DialogAndroid.java:40: error: cannot find symbol
        ReadableMapKeySeyIterator iterator = options.keySetIterator();
        ^
  symbol:   class ReadableMapKeySeyIterator
  location: class DialogAndroid
2 errors

https://github.com/facebook/react-native/issues/3540

**Comment by redism** [comment]
:+1:

**Comment by geof90** [comment]
I have submitted a fix, please try it at my fork and verify that it works!
