### ISSUE TITLE
React native dialogs crashes in the android version below 5.0.0.

### ISSUE THREAD

**Issue by alex44jzy** [aakashns/react-native-dialogs#50]
I have used the react-native-dialogs in android verison beyond 5.0.0, it works well. But it crush out when i install the app in the android verison's 4.4.4 and 4.3. So is there any methods to support the lower android versions?

**Comment by vonovak** [comment]
can you please be more specific? what error do you get?

**Comment by vonovak** [comment]
closing as stale
