### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by ahsanazwar** [aakashns/react-native-dialogs#53]
Im trying to uninstall this library by the following command:
npm uninstall react-native-dialogs

but after uninstalling when I'm trying to run the project it giving me the it following error:

![err](https://cloud.githubusercontent.com/assets/20488590/23511174/1c2f6728-ff7e-11e6-86fe-80a346e78916.PNG)

**Comment by vonovak** [comment]
take a look at the manual installation instructions and remove the lines that are added in those instructions.
