### ISSUE TITLE
Illegal callback invocation from native module error

### ISSUE THREAD

**Issue by varungupta85** [aakashns/react-native-dialogs#57]
I am observing the below error which leads to a crash in the app.

![screen shot 2017-03-17 at 12 05 44 pm](https://cloud.githubusercontent.com/assets/7475133/24031754/5ec58602-0b0a-11e7-95ed-8b2bb696cf21.png)

Below is the excerpt from code where the error is happening

```java
if (options.hasKey("cancelListener")) {
            mBuilder.cancelListener(new DialogInterface.OnCancelListener() {
                @Override
                public void onCancel(DialogInterface dialog) {
                    callback.invoke("cancelListener");
                }
            });
        }
```

This error is occurring when a dialog box is shown on the app and the user presses the home screen and then go back into the app after some time and try to click on any of the options in the dialog box.

**Comment by gavinyeah** [comment]
I think it's caused by this change in react-native which allows the callback be invoked for only once:

[Fail-Fast on Redundant Java Callback Invocations ](https://github.com/facebook/react-native/commit/e64618374b2e23ddd0ec91b777c2677c19ac5de3)

However, our dialog will invoke the callback for multiple times, e.g., select an option, press ok will invoke twice at least.

**Comment by varungupta85** [comment]
Does that mean that this package can't be used for those usecases, mainly a radio or checkbox selection. For me, it started to occur for simple alert boxes when I introduced a cancel listener to perform a few things when a user taps outside the alert box to cancel it. I just ended up not adding the cancel listener and making the alert uncancellable for cases in which I need to perform some actions before the alert box can be cancelled.

**Comment by vonovak** [comment]
yes, callback can only be invoked once. If you'd like to have your JS function to be called multiple times, we'd need to use events. This is currently not implemented but I'd merge a PR for this if anyone is interested.

**Comment by varungupta85** [comment]
hi @vonovak, I am interested in this functionality. Currently, I am not able to use `react-native-dialogs` in some cases because of this limitation and have to create my own component for those use-cases.

**Comment by vonovak** [comment]
@varungupta85 if you're interested in this functionality, you can create a PR that will allow the native module to send events to JS, as outlined in the [docs](https://facebook.github.io/react-native/docs/native-modules-android.html#sending-events-to-javascript)

**Comment by Noitidart** [comment]
I think this is also a problem when we set `onNegative` at same time as `dismissListener`/`cancelListener`. It seems to invoke the onNegative, and then tries to invoke dismissListener/cancelListener. So if we supply a `onNegative` we can't supply a dismissListener/cancelListener, is this true?
