### ISSUE TITLE
How to change the positive button style?

### ISSUE THREAD

**Issue by rajsuvariya** [aakashns/react-native-dialogs#58]
Is there any option to change the color and style of positive button?

**Comment by Fuhrmann** [comment]
To change the color of the positive button you can use:

positiveColor: 'red'

![image](https://user-images.githubusercontent.com/1160365/32861456-8029bcbc-ca33-11e7-92bd-32b13a2c7a26.png)

**Comment by vonovak** [comment]
please see https://github.com/aakashns/react-native-dialogs/issues/20
