### ISSUE TITLE
Undefined is not an object (evaluation 'NativeModules.DialogAndroid.show')

### ISSUE THREAD

**Issue by Duvieusam** [aakashns/react-native-dialogs#60]
I'm having this issue when I call the function show().

Here is my code : 

```
const options = {
      title: 'Hello, World!',
      content: 'I\'m just simple Dialog',
      positiveText: 'OK',
      negativeText: 'Cancel'
};

const dialog = new DialogAndroid()

dialog.set(options);
dialog.show();
```

Thanks

**Comment by cameronmoreau** [comment]
make sure to run `react-native link react-native-dialogs` and then reinstall the app. Just running  link didn't work for me.

**Comment by johngoren** [comment]
Didn't work for me...

**Comment by vonovak** [comment]
This is a clear indicator of the module not being linked correctly. Please follow the installation instructions carefully.
