### ISSUE TITLE
App crash when itemsCallbackSingleChoice is invoked without selecting any options

### ISSUE THREAD

**Issue by dbertella** [aakashns/react-native-dialogs#61]
I found this weird behaviour, it isn't happening with multiple choices or itemsCallback, just with single choices.

I'm running `react-native-dialogs` v. 0.0.19 and `react-native` v. 0.44.0

Here is an example of what is happening to me, is there any work around for it?
![singlechoicebug](https://cloud.githubusercontent.com/assets/2563196/26410132/4d0f1b2e-409a-11e7-9566-c5747545be07.gif)

**Comment by npaez** [comment]
Same problem here, I fixed with a preselected option,

`"selectedIndex": INDEX_OF_ARRAY`

It may not be the best solution, but it worked in my case.

**Comment by vzaramel** [comment]
I did a PR trying to solve this
https://github.com/aakashns/react-native-dialogs/pull/68

**Comment by vonovak** [comment]
this is now fixed, the PR was merged
