### ISSUE TITLE
Could not find com.github.afollestad.material-dialogs:commons:0.8.6.2

### ISSUE THREAD

**Issue by jonolock91** [aakashns/react-native-dialogs#62]
Dependency couldn't be found when trying to build release
`Could not find com.github.afollestad.material-dialogs:commons:0.8.6.2`

**Comment by jonolock91** [comment]
Sorry I was missing the repository code after re-installaing a project.

```
repositories {
    maven { url "https://jitpack.io" }
}
```

**Comment by jonolock91** [comment]
Coming across this issue 1 year later helped me fix the same issue!

**Comment by Noitidart** [comment]
How did you fix it?

**Comment by jonolock91** [comment]
I just added the above code and then it worked. What issue are you getting?
