### ISSUE TITLE
Is there a way to show multiple of these dialogs on the same screen stacked over one another?

### ISSUE THREAD

**Issue by varungupta85** [aakashns/react-native-dialogs#63]
Currently, if I try to show more than one dialog box, only the latest one stays on the screen and the rest are automatically removed. Is there a way to show more than one dialog box? The `Alert` provided by react-native does show multiple dialog boxes in iOS.

**Comment by vonovak** [comment]
this is not supported, and is not planned. Also, this seems like a very strange UX pattern to me.

**Comment by varungupta85** [comment]
Okay. For me, I use this pattern when multiple parts of the app can show alerts that require user intervention. I wanted to keep those modules separate and not depend on some complex if-else logic to show an aggregated alert. This would be a corner case in the app but I need to handle it regardless.
