### ISSUE TITLE
is this repo dead?

### ISSUE THREAD

**Issue by vonovak** [aakashns/react-native-dialogs#69]
There have been no commits in a while, last release on npm a year ago. @aakashns are you still active in this repo or are you looking for maintainers? I'd volunteer, we use this in production.

**Comment by vonovak** [comment]
@aakashns any news on this? thanks

**Comment by aakashns** [comment]
Hi @vonovak,
Apologies for the delayed response. I'm not actively working on this repo (nor using this in production), so I've done a poor job maintaining it. Would be really great to have you on as a collaborator if you are interested.

I'm adding you as a collaborator on Github right now. When you are ready to publish a new version to npm, let me know and I'll figure out how to give you publishing rights for npm.

**Comment by vonovak** [comment]
Hi @aakashns,  thanks for adding me as a collaborator. I just merged one PR and would like to publish. If you can set that up with npm, that would be great. My username on npm is the same as on github.com, and my email is also this username at gmail.com

Thanks :)

**Comment by vonovak** [comment]
@aakashns could you please add me to npm? thanks! :)

**Comment by aakashns** [comment]
@vonovak I have added you to npm, can you please try publishing.

**Comment by vonovak** [comment]
@aakashns have you pushed your latest changes? the last commit here says 0.0.19, but there is 0.0.20 on npm now

**Comment by aakashns** [comment]
Yes, I have pushed the latest changes. I was testing out my npm credentials. Feel free to publish new versions.
