### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by niftylettuce** [aakashns/react-native-dialogs#8]
Per https://github.com/aakashns/react-native-dialogs/blob/269f1baf312dd887998fd183f05e3d44aaa86b60/android/src/main/java/com/aakashns/reactnativedialogs/modules/DialogAndroid.java#L92-L109 and https://github.com/afollestad/material-dialogs#progress-dialogs

**Comment by niftylettuce** [comment]
Can we please get this finished and documented?  It's a great addition.

**Comment by aakashns** [comment]
Hi @niftylettuce, sorry I haven't had the time to work on the determinate progress bar because it is a little more involved and needs some investigation.

**Comment by vonovak** [comment]
just note that guidelines say "Avoid ProgressDialog": https://developer.android.com/guide/topics/ui/dialogs.html

> Android includes another dialog class called ProgressDialog that shows a dialog with a progress bar. However, if you need to indicate loading or indeterminate progress, you should instead follow the design guidelines for Progress & Activity and use a ProgressBar in your layout.

**Comment by Noitidart** [comment]
Agreed on the design, however sometimes a ProgressDialog is required, i have multiple use cases. It would be awesome if this could be added.

**Comment by Noitidart** [comment]
Documented the indeterminate style - https://github.com/aakashns/react-native-dialogs/pull/79

**Comment by vonovak** [comment]
solved
