### ISSUE TITLE
Is it ok if I update to 1.0.0-rc1 and npm publish?

### ISSUE THREAD

**Issue by Noitidart** [aakashns/react-native-dialogs#85]
Per @aakashns comment - https://github.com/aakashns/react-native-dialogs/pull/82#issuecomment-389433568

@vonovak is it ok if I update package.json on master to have version 1.0.0-rc1 and then run npm publish?

I have published some packages to npm but I don't know if I followed proper protocol. Is the above all that we need to do?

**Comment by vonovak** [comment]
yes, having a release candidate sounds good, please go ahead. I think you want to run `npm publish` with the next tag: `--tag next`. Thanks!

**Comment by Noitidart** [comment]
Awesome thank you! I'm learning stuff here I never did it like that. Just published. I'm installing now to test.

**Comment by Noitidart** [comment]
Published and tested! :)
