### ISSUE TITLE
readme no match the react-native-dialogs version

### ISSUE THREAD

**Issue by waterFallFlow** [aakashns/react-native-dialogs#87]
The readme prepares for the 1.0.0.   but the result is 0.0.21 when i yarn add react-native-dialogs.
It works when i replace the `DialogsAndroid.js` && `DialogsAndroid.java` && `build.gradle` in the node_modules

**Comment by Noitidart** [comment]
Hi @waterFallFlow - we are in transition mode to v1 - please use `npm i react-native-dialogs@next`. We hope to bring this to `latest` tag very soon.

**Comment by waterFallFlow** [comment]
@Noitidart Thanks for the instant feedback~ Waiting for great version

**Comment by Noitidart** [comment]
Thanks @waterFallFlow ! :) Please try `npm i react-native-dialogs@next` and please share how it goes! :)

**Comment by waterFallFlow** [comment]
![image](https://user-images.githubusercontent.com/15437785/40826838-6d7b6b58-65ae-11e8-8814-a82b75b1d3ca.png)

**Comment by Noitidart** [comment]
@waterFallFlow trying doing `npm install react-native-dialogs@next` please.

**Comment by waterFallFlow** [comment]
@Noitidart 
![image](https://user-images.githubusercontent.com/15437785/40829127-2644d164-65b5-11e8-85c4-764953bfaa7d.png)
I have tried other repo like `npm install react-native-qrcode` and it worked

**Comment by Noitidart** [comment]
Oh gosh that is super duper weird. Did you uninstall the old version of react-native-dialogs first? Thist might impact. I just tried it in a new repo and it worked for me - https://i.imgur.com/EKHs8a7.png

**Comment by waterFallFlow** [comment]
Oh ~ that\`s real wired. I tried again in other project that never install this repo. but failed......（my node version is v9.10.1）
![image](https://user-images.githubusercontent.com/15437785/40829955-986d7d66-65b7-11e8-8be0-f7550b5cec6a.png)

**Comment by waterFallFlow** [comment]
@Noitidart I have used the v1.0.0 by change the node_modules files.  That \`s real nice! Hope to be more perfect later~

**Comment by Noitidart** [comment]
@waterFallFlow so doing `npm un react-native-dialogs` then `npm i react-native-dialogs@1.0.0-rc.1` works? :)

**Comment by waterFallFlow** [comment]
@Noitidart  I change my node to V6.11.3.  That\`s the report:
![image](https://user-images.githubusercontent.com/15437785/40830821-f30429a8-65b9-11e8-8514-7c3351ebfe64.png)

**Comment by Noitidart** [comment]
Oh gosh this is weird. i'm not able to figure this out. :( @vonovak any ideas? Did I publish it wrong? Should we just publish it to `latest` instead of `next`?

**Comment by vonovak** [comment]
`yarn add react-native-dialogs@next` works for me and also for noitidart so I think there is nothing wrong on our side. Also, kindly do not tag me, I'm busy and won't be able to help. Thanks.

**Comment by Noitidart** [comment]
Thanks @vonovak very much for that test when you are busy. Apologies there.

**Comment by aakashns** [comment]
@Noitidart I've added a note to the README to indicate that the current docs are for an upcoming version, as it seems to be confusing to many people.

Let's aim to release the proper 1.0.0 version on Monday, and finish all the testing before. I can do some testing over the weekend.

**Comment by waterFallFlow** [comment]
@Noitidart  My friend tried it successfully. It \`s my issue. Thanks for your patience.

**Comment by Noitidart** [comment]
@aakashns thanks very much! I did some tests by using it in prouction. One interesting find I made was it doesn't work with `appcompat:v7:27` - https://github.com/aakashns/react-native-dialogs/pull/86#issuecomment-393715324

**Comment by aakashns** [comment]
I've published 1.0.0. We'll look into issues as they come up.
