### ISSUE TITLE
Turn off autocorrect on prompts

### ISSUE THREAD

**Issue by ferdicus** [aakashns/react-native-dialogs#99]
When using `DialogAndroid.prompt` the `TextInput` will autocorrect input by default... which is kinda annoying.

Can we provide an option that disables this?

**Comment by ferdicus** [comment]
I patched the source file in react-native-dialogs in order to achieve what I wanted:

file:
`reactnativedialogs/modules/DialogAndroid.java`
make sure to import input types on top of file:
`+ import android.text.InputType;`

and replace this (368-370):
`- if (input.hasKey("type")) {`
`-   mBuilder.inputType(input.getInt("type"));`
`- }`

with this:
`+ mBuilder.inputType(InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);`


Notice, you will get a default text keyboard WITHOUT suggestions

**Comment by ferdicus** [comment]
closing this

**Comment by Noitidart** [comment]
This is something that we should introduce into the lib.
